### ISSUE TITLE
[Suggest] use same Gateway to both service 

### ISSUE THREAD

**Issue by MahmoudMabrok** [AbdElraoufSabri/GADSLeaderboard#1]
you have two **Gateways** with different baseUrl 
you can use only one to do the same function
but what about **baseUrl**? 

here comes the power of **@Url** annotation with your service it will allow you to pass full URL as params.
[full code](https://github.com/MahmoudMabrok/GadsBoard2020/blob/master/app/src/main/java/edu/mahmoudmabrok/gadsboard/dataLayer/repo/LeaderAPI.kt)

```
  @POST
    @FormUrlEncoded
    fun submit(
        @Url newBase: String = "https://docs.google.com/forms/d/e/1FAIpQLSf9d1TcNU6zc6KR8bSEM41Z1g1zl35cwZr2xyjIhaMAz8WChQ/formResponse",
        @Field("entry.1877115667")
        firstName: String,
        @Field("entry.2006916086")
        lastName: String,
        @Field("entry.1824927963")
        emailtName: String,
        @Field("entry.284483984")
        link: String
    ): Single<Unit>
```

**Comment by AbdElraoufSabri** [comment]
Thank you for the suggestion :) If I've time I'd fix it.

**Comment by MahmoudMabrok** [comment]
I can do it as PR if u want @AbdElraoufSabri
